### PR TITLE
[WIP] Add medium & fingering style

### PR DESCRIPTION
**Pull request by paulgoetze**
Adds the styles `medium` and `fingering`.
Fixes the fingering part of #1.

There is still a small bug with the layout of the circles sometimes, e.g.:

     uke-chords Cmaj7 --style fingering

grafik

### CODE REVIEW

**Comment by peanutbutterandcrackers** [comment]
Great! Thank you, sir!

However, I have a few feedback. First and foremost, I would like to request that you use this site as a reference for the finger numbers (it has got a good catalogue of it): https://ukulele-chords.com/

In the case of Cmaj7 (as shown in the screenshot), the chord is played with finger no. 2 (rather than no. 1): https://ukulele-chords.com/Cmaj7. This has the advantage of being able to smoothly transition between the chords C-Cmaj7-C7 with fingers 3, 2 and 1 respectively (in the song 'Raindrops keep falling on my head, at the very least). That should be a lot of help to beginners.

You are doing a marvellous work, good sir! :+1:

**Comment by paulgoetze** [comment]
Thanks @peanutbutterandcrackers for the feedback! Very valid, I’ll have a look at the fingerings as given on https://ukulele-chords.com and adjust them accordingly.

**Comment by janlelis** [comment]
Awesome thanks for the feature, released as 1.0.1!

Maybe we could just duplicate chords that have multiple popular fingering options.

**Comment by peanutbutterandcrackers** [comment]
@janlelis - Uh, uh... I just installed the latest version and it has the bugs that @paulgoetze was going to fix...

Also, @paulgoetze - What exactly does the --style medium do? Just the black markers? o.O

I am sorry I do not understand

**Comment by paulgoetze** [comment]
Yeah, that’s why it was tagged "Work in progress". Actually wanted to fix that, but @janlelis was faster ;) 
Will try to fix that soonish, and also double-check the numbers according to ukulele-chords.com.

@peanutbutterandcrackers yes, it just adjusts the size of the circles on the fretboard.
Options are [small, medium, large, fingering]. Probably having one default + the fingering is enough.
Or maybe even put the fingering as default. What do you think, @janlelis?

**Comment by peanutbutterandcrackers** [comment]
Then may I suggest that we have a separate `--show-finger` or some other type of option to show fingers, please? That way it won't be confused with other styles...

Also, may I report another bug with the medium style? This:
screenshot at 2018-10-10 17-40-39
A. It is actually larger than the `large` style
B. The open string makers are a bit off

Sorry to bother you with all these problems

**Comment by peanutbutterandcrackers** [comment]
Perhaps this should be tested a bit more, because with the default settings this isn't working on Linux Mint. And there might be quite a lot of other distros out there where this would only malfunction. Perhaps something else could be done that would make it font-agnostic?

**Pull request merged**
